<?php

namespace ContainerF0LhY8Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2pmohY5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2pmohY5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2pmohY5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['privates', '.errored.R.IJrXS', NULL, 'Cannot determine controller argument for "App\\Controller\\EvennementfrontController::search()": the $doctrine argument is type-hinted with the non-existent class or interface: "App\\Controller\\ManagerRegisrty". Did you forget to add a use statement?'],
        ], [
            'doctrine' => '?',
        ]);
    }
}
