<?php

namespace ContainerF0LhY8Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CQV7BicService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CQV7Bic' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CQV7Bic'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'evennementRepository' => ['privates', 'App\\Repository\\EvennementRepository', 'getEvennementRepositoryService', true],
        ], [
            'doctrine' => '?',
            'evennementRepository' => 'App\\Repository\\EvennementRepository',
        ]);
    }
}
