<?php

namespace ContainerF0LhY8Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Iy_Q3nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iy_.Q3n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iy_.Q3n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'eventRepo' => ['privates', 'App\\Repository\\EvennementRepository', 'getEvennementRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'doctrine' => '?',
            'eventRepo' => 'App\\Repository\\EvennementRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
