<?php

namespace Container3RCD1Im;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNumMediaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FUGPmyG.App\Entity\NumMedia' shared service.
     *
     * @return \App\Entity\NumMedia
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.FUGPmyG": it references class "App\\Entity\\NumMedia" but no such service exists.');
    }
}
