<?php

namespace ContainerZZi9IZF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U41L8JpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u41L8Jp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u41L8Jp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored..service_locator.u41L8Jp.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.u41L8Jp": it references class "App\\Entity\\Article" but no such service exists.'],
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
        ], [
            'article' => 'App\\Entity\\Article',
            'commentRepository' => 'App\\Repository\\CommentRepository',
        ]);
    }
}
