<?php

namespace ContainerLHJx6NR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HXWB3r1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HXWB3r1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HXWB3r1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'professionnelSante' => ['privates', '.errored..service_locator.HXWB3r1.App\\Entity\\ProfessionnelSante', NULL, 'Cannot autowire service ".service_locator.HXWB3r1": it references class "App\\Entity\\ProfessionnelSante" but no such service exists.'],
            'professionnelSanteRepository' => ['privates', 'App\\Repository\\ProfessionnelSanteRepository', 'getProfessionnelSanteRepositoryService', true],
        ], [
            'professionnelSante' => 'App\\Entity\\ProfessionnelSante',
            'professionnelSanteRepository' => 'App\\Repository\\ProfessionnelSanteRepository',
        ]);
    }
}
