<?php

namespace ContainerLHJx6NR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPatientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KAlXsed.App\Entity\Patient' shared service.
     *
     * @return \App\Entity\Patient
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KAlXsed": it references class "App\\Entity\\Patient" but no such service exists.');
    }
}
