<?php

namespace ContainerLHJx6NR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfessionnelSante2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Zyk16jE.App\Entity\ProfessionnelSante' shared service.
     *
     * @return \App\Entity\ProfessionnelSante
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Zyk16jE": it references class "App\\Entity\\ProfessionnelSante" but no such service exists.');
    }
}
