<?php

namespace ContainerONxTf2N;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JMGuJiuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JMGuJiu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JMGuJiu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PostController::delete' => ['privates', '.service_locator.JQ.Ubn6', 'get_ServiceLocator_JQ_Ubn6Service', true],
            'App\\Controller\\PostController::edit' => ['privates', '.service_locator.JQ.Ubn6', 'get_ServiceLocator_JQ_Ubn6Service', true],
            'App\\Controller\\PostController::index' => ['privates', '.service_locator.Xf_chUG', 'get_ServiceLocator_XfChUGService', true],
            'App\\Controller\\PostController::new' => ['privates', '.service_locator.Xf_chUG', 'get_ServiceLocator_XfChUGService', true],
            'App\\Controller\\PostController::show' => ['privates', '.service_locator.4WI1Dtz', 'get_ServiceLocator_4WI1DtzService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\PostController:delete' => ['privates', '.service_locator.JQ.Ubn6', 'get_ServiceLocator_JQ_Ubn6Service', true],
            'App\\Controller\\PostController:edit' => ['privates', '.service_locator.JQ.Ubn6', 'get_ServiceLocator_JQ_Ubn6Service', true],
            'App\\Controller\\PostController:index' => ['privates', '.service_locator.Xf_chUG', 'get_ServiceLocator_XfChUGService', true],
            'App\\Controller\\PostController:new' => ['privates', '.service_locator.Xf_chUG', 'get_ServiceLocator_XfChUGService', true],
            'App\\Controller\\PostController:show' => ['privates', '.service_locator.4WI1Dtz', 'get_ServiceLocator_4WI1DtzService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\PostController::delete' => '?',
            'App\\Controller\\PostController::edit' => '?',
            'App\\Controller\\PostController::index' => '?',
            'App\\Controller\\PostController::new' => '?',
            'App\\Controller\\PostController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\PostController:delete' => '?',
            'App\\Controller\\PostController:edit' => '?',
            'App\\Controller\\PostController:index' => '?',
            'App\\Controller\\PostController:new' => '?',
            'App\\Controller\\PostController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
