<?php

<<<<<<< HEAD:var/cache/dev/ContainerONxTf2N/getPost2Service.php
namespace ContainerONxTf2N;

=======
namespace ContainerZmekEeS;
>>>>>>> d54b9b8a16ff5945f42ca699395393e80e91368d:var/cache/dev/ContainerZmekEeS/getResponseService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPost2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.JQ.Ubn6.App\Entity\Post' shared service.
     *
     * @return \App\Entity\Post
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.JQ.Ubn6": it references class "App\\Entity\\Post" but no such service exists.');
    }
}
