<?php

<<<<<<< HEAD:var/cache/dev/ContainerONxTf2N/getResponseService.php
namespace ContainerONxTf2N;

=======
namespace ContainerBrRp53y;
>>>>>>> d54b9b8a16ff5945f42ca699395393e80e91368d:var/cache/dev/ContainerBrRp53y/getResponseService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResponseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bRdave9.Symfony\Component\HttpFoundation\Response' shared service.
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.bRdave9": it references class "Symfony\\Component\\HttpFoundation\\Response" but no such service exists.');
    }
}
