<?php

namespace ContainerMGYDvdx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FUGPmyGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FUGPmyG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FUGPmyG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'numMedia' => ['privates', '.errored..service_locator.FUGPmyG.App\\Entity\\NumMedia', NULL, 'Cannot autowire service ".service_locator.FUGPmyG": it references class "App\\Entity\\NumMedia" but no such service exists.'],
            'numMediaRepository' => ['privates', 'App\\Repository\\NumMediaRepository', 'getNumMediaRepositoryService', true],
        ], [
            'numMedia' => 'App\\Entity\\NumMedia',
            'numMediaRepository' => 'App\\Repository\\NumMediaRepository',
        ]);
    }
}
