<?php

namespace ContainerZQLeLtv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KV5epv5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kV5epv5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kV5epv5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', true],
        ], [
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
            'serializer' => '?',
        ]);
    }
}
