<?php

namespace ContainerZQLeLtv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2nHEpthService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2nHEpth' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2nHEpth'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'articleLikeRepository' => ['privates', 'App\\Repository\\ArticleLikeRepository', 'getArticleLikeRepositoryService', true],
            'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
        ], [
            'articleLikeRepository' => 'App\\Repository\\ArticleLikeRepository',
            'articleRepository' => 'App\\Repository\\ArticleRepository',
        ]);
    }
}
