<?php

namespace ContainerJmPAyZn;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ItRGNcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._ItRGNc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._ItRGNc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\EvennementController::delete' => ['privates', '.service_locator.t6ro.NA', 'get_ServiceLocator_T6ro_NAService', true],
            'App\\Controller\\EvennementController::edit' => ['privates', '.service_locator.t6ro.NA', 'get_ServiceLocator_T6ro_NAService', true],
            'App\\Controller\\EvennementController::index' => ['privates', '.service_locator.HMUAAHF', 'get_ServiceLocator_HMUAAHFService', true],
            'App\\Controller\\EvennementController::new' => ['privates', '.service_locator.HMUAAHF', 'get_ServiceLocator_HMUAAHFService', true],
            'App\\Controller\\EvennementController::show' => ['privates', '.service_locator.f6mvX9L', 'get_ServiceLocator_F6mvX9LService', true],
            'App\\Controller\\EvennementfrontController::index' => ['privates', '.service_locator.HMUAAHF', 'get_ServiceLocator_HMUAAHFService', true],
            'App\\Controller\\SignupController::addUser' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\VideoController::delete' => ['privates', '.service_locator.JgKnByv', 'get_ServiceLocator_JgKnByvService', true],
            'App\\Controller\\VideoController::edit' => ['privates', '.service_locator.JgKnByv', 'get_ServiceLocator_JgKnByvService', true],
            'App\\Controller\\VideoController::index' => ['privates', '.service_locator.ErqXzhI', 'get_ServiceLocator_ErqXzhIService', true],
            'App\\Controller\\VideoController::new' => ['privates', '.service_locator.ErqXzhI', 'get_ServiceLocator_ErqXzhIService', true],
            'App\\Controller\\VideoController::show' => ['privates', '.service_locator.QGG8A4p', 'get_ServiceLocator_QGG8A4pService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\EvennementController:delete' => ['privates', '.service_locator.t6ro.NA', 'get_ServiceLocator_T6ro_NAService', true],
            'App\\Controller\\EvennementController:edit' => ['privates', '.service_locator.t6ro.NA', 'get_ServiceLocator_T6ro_NAService', true],
            'App\\Controller\\EvennementController:index' => ['privates', '.service_locator.HMUAAHF', 'get_ServiceLocator_HMUAAHFService', true],
            'App\\Controller\\EvennementController:new' => ['privates', '.service_locator.HMUAAHF', 'get_ServiceLocator_HMUAAHFService', true],
            'App\\Controller\\EvennementController:show' => ['privates', '.service_locator.f6mvX9L', 'get_ServiceLocator_F6mvX9LService', true],
            'App\\Controller\\EvennementfrontController:index' => ['privates', '.service_locator.HMUAAHF', 'get_ServiceLocator_HMUAAHFService', true],
            'App\\Controller\\SignupController:addUser' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\VideoController:delete' => ['privates', '.service_locator.JgKnByv', 'get_ServiceLocator_JgKnByvService', true],
            'App\\Controller\\VideoController:edit' => ['privates', '.service_locator.JgKnByv', 'get_ServiceLocator_JgKnByvService', true],
            'App\\Controller\\VideoController:index' => ['privates', '.service_locator.ErqXzhI', 'get_ServiceLocator_ErqXzhIService', true],
            'App\\Controller\\VideoController:new' => ['privates', '.service_locator.ErqXzhI', 'get_ServiceLocator_ErqXzhIService', true],
            'App\\Controller\\VideoController:show' => ['privates', '.service_locator.QGG8A4p', 'get_ServiceLocator_QGG8A4pService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\EvennementController::delete' => '?',
            'App\\Controller\\EvennementController::edit' => '?',
            'App\\Controller\\EvennementController::index' => '?',
            'App\\Controller\\EvennementController::new' => '?',
            'App\\Controller\\EvennementController::show' => '?',
            'App\\Controller\\EvennementfrontController::index' => '?',
            'App\\Controller\\SignupController::addUser' => '?',
            'App\\Controller\\VideoController::delete' => '?',
            'App\\Controller\\VideoController::edit' => '?',
            'App\\Controller\\VideoController::index' => '?',
            'App\\Controller\\VideoController::new' => '?',
            'App\\Controller\\VideoController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\EvennementController:delete' => '?',
            'App\\Controller\\EvennementController:edit' => '?',
            'App\\Controller\\EvennementController:index' => '?',
            'App\\Controller\\EvennementController:new' => '?',
            'App\\Controller\\EvennementController:show' => '?',
            'App\\Controller\\EvennementfrontController:index' => '?',
            'App\\Controller\\SignupController:addUser' => '?',
            'App\\Controller\\VideoController:delete' => '?',
            'App\\Controller\\VideoController:edit' => '?',
            'App\\Controller\\VideoController:index' => '?',
            'App\\Controller\\VideoController:new' => '?',
            'App\\Controller\\VideoController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
