<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6isjx4a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6isjx4a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6isjx4a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6isjx4a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6isjx4a\App_KernelDevDebugContainer([
    'container.build_hash' => '6isjx4a',
    'container.build_id' => '3cbdee9a',
    'container.build_time' => 1677529595,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6isjx4a');
