<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS8svFts\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS8svFts/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS8svFts.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS8svFts\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS8svFts\App_KernelDevDebugContainer([
    'container.build_hash' => 'S8svFts',
    'container.build_id' => 'b2babe09',
    'container.build_time' => 1678311849,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS8svFts');
