<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerONxTf2N\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerONxTf2N/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerONxTf2N.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerONxTf2N\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerONxTf2N\App_KernelDevDebugContainer([
    'container.build_hash' => 'ONxTf2N',
    'container.build_id' => '9dfa1686',
    'container.build_time' => 1676845106,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerONxTf2N');
