<?php

namespace ContainerBjxrRaM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UZyvraoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uZyvrao' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uZyvrao'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'flashy' => ['services', 'mercuryseries_flashy.flashy_notifier', 'getMercuryseriesFlashy_FlashyNotifierService', true],
            'repository' => ['privates', 'App\\Repository\\EvennementRepository', 'getEvennementRepositoryService', true],
        ], [
            'doctrine' => '?',
            'flashy' => '?',
            'repository' => 'App\\Repository\\EvennementRepository',
        ]);
    }
}
