<?php

namespace ContainerBjxrRaM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EoK4IyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Eo_k4Iy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Eo_k4Iy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evennementRepository' => ['privates', 'App\\Repository\\EvennementRepository', 'getEvennementRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'evennementRepository' => 'App\\Repository\\EvennementRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
