<?php

namespace ContainerBjxrRaM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_R_IJrXSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.R.IJrXS' shared service.
     *
     * @return \App\Controller\ManagerRegisrty
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\EvennementfrontController::search()": the $doctrine argument is type-hinted with the non-existent class or interface: "App\\Controller\\ManagerRegisrty". Did you forget to add a use statement?');
    }
}
